# Generated by Django 4.2.4 on 2023-08-04 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='asesor',
        ),
    ]
